export const allowedTags = [
  "array",
  "string",
  "hash table",
  "dynamic programming",
  "math",
  "depth-first search",
  "sorting",
  "greedy",
  "database",
  "breadth-first search",
  "tree",
  "binary search",
  "matrix",
  "binary tree",
  "two pointers",
  "bit manipulation",
  "stack",
  "design",
  "heap",
  "graph",
  "backtracking",
  "simulation",
  "prefix sum",
  "counting",
  "sliding window",
  "linked list",
  "union find",
  "recursion",
  "ordered set",
  "monotonic stack",
  "binary search tree",
  "trie",
  "divide and conquer",
  "bitmask",
  "queue",
  "enumeration",
  "geometry",
  "memoization",
  "game theory",
  "segment tree",
  "topological sort",
  "hash function",
  "interactive",
  "binary indexed tree",
  "data stream",
  "string matching",
  "rolling hash",
  "shortest path",
  "randomized",
  "number theory",
  "combinatorics",
  "monotonic queue",
  "iterator",
  "merge sort",
  "concurrency",
  "brainteaser",
  "probability and statistics",
  "doubly-linked list",
  "quickselect",
  "bucket sort",
  "minimum spanning tree",
  "counting sort",
  "suffix array",
  "shell",
  "line sweep",
  "reservoir sampling",
  "eulerian circuit",
  "strongly connected component",
  "radix sort",
  "rejection sampling",
];
